<script setup lang="ts">
useSeoMeta({
  title: "Secure Blockchain-Based Advertising Solutions | Ad-Yo",
  description: "Explore Ad-Yo ecosystem, created to improve ad targeting, promote data authenticity and security, ensure a fair distribution of profits."
});

const SWIPER_DELAY = 6000;

const nftProfileCopy = [
  "When a new customer registers, a generative art NFT is created.",
  "The NFT in encrypted form represents a visualization of a set of the customer's interests, preferences and values.",
  "Active customers make their NFT evolve by upgrading their profile with their actions.",
  "When a customer levels up, their NFT changes and acquires new features, reflecting the evolution of their interests and actions.",
  "Customers levels up depending on the fulfillment of tasks set by advertisers. As their profile evolves and the dynamic NFT acquires new features, the rarity and therefore the value of the NFT goes up.",
  "Customers can display their profile NFTs as standalone digital art objects on OpenSea, Refinable, Rarible, NFTICALLY, NFTrade and other marketplaces.",
];

</script>

<template>
  <section class="wrapper flex flex-col w-full">
    <div class="lg:flex [&>*]:flex-1 w-full items-center gap-20">
      <h1 class="mb-10 md:mb-14 lg:mb-0">Ad-Yo technology, protocol and NFT profile</h1>
      <h2>Decentralized platform for depersonalized data trading</h2>
    </div>
    <div class="flex flex-col w-full grow items-center justify-center">
      <img src="/images/tech_scheme_1.webp" alt="Technology scheme" width="2020" height="714" loading="lazy" class="w-full lg:w-4/5 hidden xl:block" />
      <img src="/images/tech_scheme_1_mob.svg" alt="Technology scheme" width="325" height="822" class="w-full max-w-[400px] mt-14 xl:hidden" />
    </div>
  </section>

  <section class="wrapper flex flex-col grow" id="nft-profile">
    <h2 class="h1 mb-20">NFT profile</h2>

    <div class="hidden xl:grid grid-cols-3 grid-rows-2 gap-y-20">
      <ElementsTechNFTItem v-for="(text, index) in nftProfileCopy" :key="index" :num="index + 1" :num-first="index < 3" :text="text" />
    </div>

    <div class="xl:hidden flex grow items-center">
      <Swiper
        :modules="[SwiperAutoplay]"
        :space-between="0"
        :slides-per-view="1"
        :autoplay="{
          delay: SWIPER_DELAY,
          disableOnInteraction: true
        }"
        :breakpoints="{
              890: {
                slidesPerView: 2,
                spaceBetween: 40,
                autoplay: {
                  delay: SWIPER_DELAY * 2,
                  disableOnInteraction: true,
                }
              },
            }"
        >
        <SwiperSlide v-for="(text, index) in nftProfileCopy" :key="index">
          <ElementsTechNFTItem :num="index + 1" :num-first="true" :text="text" />
        </SwiperSlide>
      </Swiper>
    </div>
  </section>

  <section class="wrapper" id="protocol">
    <h2 class="mb-10 md:mb-20 h1">Protocol</h2>
    <div class="flex gap-14 flex-col md:flex-row [&>*]:flex-1 [&>.text-block]:space-y-12">

      <div class="w-full order-1 md:order-none grow bg-tech-protocol wrapper flex items-center justify-center">
        <video class="mix-blend-multiply max-w-full max-h-full" muted autoplay loop>
          <source src="/video/tech-protocol.mp4" />
        </video>
      </div>

      <div class="text-block">
        <div class="info-block">
          <h3>Identity verification</h3>
          <p>Ad-yo customers data about preferences and interests is generated by the customers themselves. Each profile
            is unique.</p>
        </div>
        <div class="info-block">
          <h3>NFT creation</h3>
          <p>The NFT token for the customer profile is generated to embody a digital imprint of the customer's
            personality, interests and achievements.
            The digital rights belong to the customer and may be transferred at any time.</p>
        </div>
        <div class="info-block">
          <h3>Reward</h3>
          <p>The reward minus the network commission is transferred to the customer’s wallet.</p>
        </div>
      </div>

      <div class="text-block order-2 md:order-none">
        <div class="info-block">
          <h3>Data storage</h3>
          <p>The data is stored directly on customer's devices, representing only a set of hashes that makes it possible
            to select the target audience according to a specified parameters.</p>
        </div>
        <div class="info-block">
          <h3>Ad display</h3>
          <p>The advertiser selects a target group and pays to show ads to them with stablecoins. Payment goes to an
            escrow account regulated by a smart contract. Views of ads by users are confirmed by the system, and unspent
            impressions are returned to the advertiser in stablecoins.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="wrapper flex flex-col justify-center w-full" id="blockchain">
    <h2 class="h1 mb-20">Blockchain</h2>
    <div class="flex gap-12">
      <div class="w-2/3 shrink-0 flex flex-col">
        <img src="/images/tech_blockchain_scheme.svg" width="1703" height="836" alt="Blockchain scheme" />
        <div class="flex w-full [&>*]:text-center">
          <span class="w-[23.3%]">ADYO owners</span>
          <span class="w-[15%]">Vote</span>
          <span class="w-[23.3%]">Elected delegates</span>
          <span class="w-[15%]">Produces block</span>
          <span class="w-[23.3%]">Blockchain</span>
        </div>
      </div>
      <div class="space-y-12">
        <div class="info-block">
          <h3 class="h2">Validation</h3>
          <p>Ad campaign are validated by a number of random validators.</p>
        </div>

        <div class="info-block">
          <h3 class="h2">ADYO</h3>
          <p>ADYO service tokens are used for staking by validators and censor (confirm to reject) advertising
            campaigns.</p>
        </div>

        <div class="info-block">
          <h3 class="h2">Network fee</h3>
          <p>The network receives a fee from all transactions and distributes it between validators in accordance with
            the share of the staking.</p>
        </div>

        <div class="info-block">
          <h3 class="h2">Storage</h3>
          <p>Advertising campaigns files are stored with the IPFS</p>
        </div>
      </div>
    </div>
  </section>
</template>
