<script setup lang="ts">
useSeoMeta({
  title: "Secure Blockchain-Based Advertising Solutions | Ad-Yo",
  description: "Explore Ad-Yo ecosystem, created to improve ad targeting, promote data authenticity and security, ensure a fair distribution of profits."
});
</script>

<template>
  <section class="wrapper flex flex-col w-full">
    <div class="flex [&>*]:flex-1 w-full items-center gap-20">
      <h1>Ad-Yo technology, protocol and NFT profile</h1>
      <h2>Decentralized platform for depersonalized data trading</h2>
    </div>
    <div class="flex flex-col w-full grow items-center justify-center">
      <img src="/images/tech_scheme_1.webp" alt="Technology scheme" width="2020" height="714" class="w-4/5" />
    </div>
  </section>

  <section class="wrapper">
    <h2 class="h1 mb-20">NFT profile</h2>
    <div class="grid grid-cols-3 grid-rows-2 gap-y-20">
      <div class="tech-nft-num">
        <img src="/images/num1.svg" width="400" height="500" alt="1" loading="lazy">
        <p>When a new customer registers, a generative art NFT is created.</p>
      </div>
      <div class="tech-nft-num">
        <img src="/images/num2.svg" width="400" height="500" alt="2" loading="lazy">
        <p>The NFT in encrypted form represents a visualization of a set of the customer's interests, preferences and
          values.</p>
      </div>
      <div class="tech-nft-num">
        <img src="/images/num3.svg" width="400" height="500" alt="3" loading="lazy">
        <p>Active customers make their NFT evolve by upgrading their profile with their actions.</p>
      </div>
      <div class="tech-nft-num">
        <p>When a customer levels up, their NFT changes and acquires new features, reflecting the evolution of their
          interests and actions.</p>
        <img src="/images/num4.svg" width="400" height="500" alt="4" loading="lazy">
      </div>
      <div class="tech-nft-num">
        <p>Customers levels up depending on the fulfillment of tasks set by advertisers. As their profile evolves and
          the dynamic NFT acquires new features, the rarity and therefore the value of the NFT goes up.</p>
        <img src="/images/num5.svg" width="400" height="500" alt="5" loading="lazy">
      </div>
      <div class="tech-nft-num">
        <p>Customers can display their profile NFTs as standalone digital art objects on OpenSea, Refinable, Rarible,
          NFTICALLY, NFTrade and other marketplaces.</p>
        <img src="/images/num6.svg" width="400" height="500" alt="6" loading="lazy">
      </div>
    </div>
  </section>

  <section class="wrapper">
    <h2 class="mb-20 h1">Protocol</h2>
    <div class="flex gap-14 [&>*]:flex-1 [&>.text-block]:space-y-12">
      <div class="w-full grow bg-tech-protocol wrapper flex items-center justify-center">
        <video class="mix-blend-multiply max-w-full max-h-full" muted autoplay loop>
          <source src="/video/tech-protocol.mp4" />
        </video>
      </div>

      <div class="text-block">
        <div class="info-block">
          <h3>Identity verification</h3>
          <p>Ad-yo customers data about preferences and interests is generated by the customers themselves. Each profile
            is unique.</p>
        </div>
        <div class="info-block">
          <h3>NFT creation</h3>
          <p>The NFT token for the customer profile is generated to embody a digital imprint of the customer's
            personality, interests and achievements.
            The digital rights belong to the customer and may be transferred at any time.</p>
        </div>
        <div class="info-block">
          <h3>Reward</h3>
          <p>The reward minus the network commission is transferred to the customer’s wallet.</p>
        </div>
      </div>

      <div class="text-block">
        <div class="info-block">
          <h3>Data storage</h3>
          <p>The data is stored directly on customer's devices, representing only a set of hashes that makes it possible
            to select the target audience according to a specified parameters.</p>
        </div>
        <div class="info-block">
          <h3>Ad display</h3>
          <p>The advertiser selects a target group and pays to show ads to them with stablecoins. Payment goes to an
            escrow account regulated by a smart contract. Views of ads by users are confirmed by the system, and unspent
            impressions are returned to the advertiser in stablecoins.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="wrapper flex flex-col justify-center w-full">
    <h2 class="h1 mb-20">Blockchain</h2>
    <div class="flex gap-12">
      <div class="w-2/3 shrink-0 flex flex-col">
        <img src="/images/tech_blockchain_scheme.svg" width="1703" height="836" alt="Blockchain scheme" />
        <div class="flex w-full [&>*]:text-center">
          <span class="w-[23.3%]">ADYO owners</span>
          <span class="w-[15%]">Vote</span>
          <span class="w-[23.3%]">Elected delegates</span>
          <span class="w-[15%]">Produces block</span>
          <span class="w-[23.3%]">Blockchain</span>
        </div>
      </div>
      <div class="space-y-12">
        <div class="info-block">
          <h3 class="h2">Validation</h3>
          <p>Ad campaign are validated by a number of random validators.</p>
        </div>

        <div class="info-block">
          <h3 class="h2">ADYO</h3>
          <p>ADYO service tokens are used for staking by validators and censor (confirm to reject) advertising
            campaigns.</p>
        </div>

        <div class="info-block">
          <h3 class="h2">Network fee</h3>
          <p>The network receives a fee from all transactions and distributes it between validators in accordance with
            the share of the staking.</p>
        </div>

        <div class="info-block">
          <h3 class="h2">Storage</h3>
          <p>Advertising campaigns files are stored with the IPFS</p>
        </div>
      </div>
    </div>
  </section>
</template>
